name: test variabile

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          USERNAME: ${{ secrets.VARIABILE }}
        run: |
          echo "$USERNAME"
